import React, { Component, useRef, useState, useCallback } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import Webcam from "react-webcam";

import imgTest from '../public/resource/01.png';

export default function Camera() {
  const [image, setImage]=useState('');
  const videoConstraints = {
    width: 300,
    height: 300,
    // facingMode: "user"
    facingMode: "environment"
  };

  const webcamRef = useRef(null);
  const capture = useCallback(
    () => {
      const imageSrc = webcamRef.current.getScreenshot();
      setImage(imgTest)
      //setImage(imageSrc)
    },
    [webcamRef]
  );

  return (
    
    <div className={styles.container}>
      <Head>
        <title>확인하기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <h3 className={styles.description}>내 몸을 바로잡는 습관</h3>
          <Link href="/">
            <a><span className={styles.mainColor}>PIO</span> 심플체커</a> 
          </Link>
        </h1>

        <h4>
          가이드 라인에 맞추어 촬영을 해주세요!
        </h4>

        <div>
          <div style={{position:'relative', width:'300px', height:'300px', border: '100px solid rgba(0,0,0,0.7)', zIndex: '1', marginBottom:'-300px'}}/>
          {image==''?<Webcam
            audio={false}
            ref={webcamRef}
            screenshotFormat="image/jpeg"
            videoConstraints={videoConstraints}
            />
            // :<img src={image}/>
            :<img style={{position:'relative', width:'300px', height:'300px'}} src='/resource/01.png'/>
          }
        </div>
        


        {image!=''?
          <div>
            <button className={styles.buttonReverse} onClick={(e)=>{e.preventDefault(); setImage(''); }}>
              다시찍기
            </button>
            <button className={styles.buttonMain} onClick={(e)=>{e.preventDefault(); setImage(''); }}>
              검사하기
            </button>
          </div>        
          :<button className={styles.capture} onClick={(e)=>{e.preventDefault(); capture(); }}>
            촬영하기
          </button>
        }

      </main>

      <footer className={styles.footer}>
        <a
          href="https://piomedical.co.kr"
          target="_blank"
          rel="noopener noreferrer"
        >
          © 2021.<span className={styles.mainColor}> PIOMEDICAL.</span> All rights reserved.{' '}
        </a>
      </footer>
    </div>
  )
}
